title: 潇之风殿
description: My Personal Blog
author: L
logo: /assets/logo.ico
github: https://github.com/liuyanfight
about: This is your life, and it’s ending one minute at a time.
disqus_shortname: liuyanfight
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Resume
      url: /resume/
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/liuyanfight
      icon: fa-github


social:
    - icon: fa-weibo
      link: 'http://weibo.com/329249870'
    - icon: fa-twitter
      link: 'https://twitter.com/liuyanfight'


share:
  twitter_username: liuyanfight
  fb_appid: 000000000000


enableTags: true
tagarray: ['Java',C]

url: "http://liuyanfight.github.io"
baseurl: "http://liuyanfight.github.io"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
